import React from "react";

const quotes = [
  "Cooking is love made visible.",
  "A recipe has no soul. You, as the cook, must bring soul to the recipe",
  "The most indispensable ingredient of all good home cooking: love for those you are cooking for.",
  "Cooking is at once child’s play and adult joy.",
  "In cooking, as in all the arts, simplicity is the sign of perfection.",
  "Cooking is like painting or writing a song. Just as there are only so many notes or colors, there are only so many flavors.",
  "The best meals are those made with love and shared with others.",
  "You don’t have to cook fancy or complicated masterpieces, just good food from fresh ingredients.",
  "When you cook, you never stop learning.",
  "The kitchen is the heart of the home.",
  "Good food ends with good talk.",
  "A pinch of patience and a dash of love make a good recipe.",
  "To cook is to express yourself.",
  "Where there is food, there is love." ,
  "Cooking is the ultimate giving.",
  "Flavors are like musical notes—when they harmonize, the dish sings.",
  "Every meal is a story waiting to be shared.",
  "Baking is love made edible.",
  "Life is what you bake of it.",
  "aking is therapy without the bill.",
  "A balanced diet is a cupcake in each hand.",
  "Cookies are made of butter and love.",
  "Stressed is just desserts spelled backwards.",
  "Bake the world a better place.",
  "Keep calm and bake on.",
  "Happiness is homemade bread.",
  "Measure twice, bake once.",
  "The secret ingredient is always love.",
  "The only running you should do is running out of cookies.",
  "Eat cake. It’s somebody’s birthday somewhere.",
  "Food is symbolic of love when words are inadequate.",
  "Overmixing muffin batter leads to dense, tough muffins.",
  "Baking powder and baking soda are not the same: one is a complete leavening agent, the other needs acid.",
  "Yeast is a living organism that feeds on sugar and produces carbon dioxide, making dough rise.",
  "Gluten forms when water mixes with flour and the dough is kneaded.",
  "Sifting flour helps remove clumps and incorporates air for lighter baked goods.",
  "Letting cookie dough chill before baking makes cookies chewier and less likely to spread.",
  "Brown sugar has molasses, which keeps baked goods moist and adds flavor.",
  "Using room temperature ingredients helps batter mix more evenly.",
  "Convection ovens bake faster because of their internal fan that circulates hot air.",
  "A cracked cheesecake is often due to overbaking or rapid cooling.",
  "Eggs add structure, moisture, and color to baked goods.",
  "Too much flour is the #1 cause of dry, tough baked goods—always spoon, not scoop!",
  "Baking at high altitudes requires adjusting temperature and ingredients.",
  "Proofing is the step where yeast dough is allowed to rise before baking.",
  "Cake flour has lower protein content than all-purpose flour, resulting in tender cakes.",
  "Butter creates flakiness in pastries by separating layers as it melts during baking.",
  "Baking stones or steels help pizzas and breads get a crisp crust.",
  "Overcrowding your baking sheet prevents even cooking—space out your cookies!",
  "Searing meat doesn't seal in juices—it just adds flavor via browning.",
  "Resting cooked meat helps redistribute juices for better texture.",
  "Salt enhances flavor—it’s not just for saltiness.",
  "Coldwater stops veggies from overcooking after blanching (called shocking).",
  "Simmering is different from boiling—it’s gentler and better for stews and sauces.",
  "Use a thermometer for accurate meat doneness instead of guessing.",
  "Deglazing lifts tasty brown bits from the pan, enriching sauces and gravies.",
  "A dull knife is more dangerous than a sharp one because it requires more force.",
  "Cast iron pans retain heat well and develop natural non-stick surfaces with use.",
  "Acids like vinegar or lemon juice brighten dishes and balance richness.",
  "Cooking onions slowly brings out their natural sugars—this is caramelizing.",
  "Marinating meat in acidtoo long can make it mushy, not tender.",
  "You can “revive” wilted herbs by soaking them in ice water.",
  "Don’t overcrowd the pan when frying—it lowers the oil temperature and makes food soggy.",
  "Preheating your pan before adding food reduces sticking and helps browning.",
  "Pasta water can be reused in sauces to add starch and flavor.",
  "Stir-frying requires very high heat and constant motion.",
  "The “umami” taste comes from glutamates and is found in tomatoes, soy sauce, and mushrooms.",
  "Cooking with the lid on traps steam—useful for braising and faster cooking.",
  "Low and slow cooking tenderizes tough cuts of meat over time.",
  "Butter is 80% fat and 20% water/milk solids.",
  "Olive oil has a lower smoke point than vegetable oil, so use it for low to medium heat.",
  "Fresh herbs lose potency quickly—dry herbs are stronger but need time to infuse.",
  "Vanilla extract comes from cured pods of the vanilla orchid.",
  "Baking powder contains both acid and base and needs only moisture and heat.",
  "Cornstarch thickens sauces without adding flavor or color.",
  "Egg yolks emulsify and enrich sauces like hollandaise or custards.",
  "Garlic becomes sweeter and less sharp the more it’s cooked.",
  "Onion varieties differ in sweetness, sharpness, and best use.",
  "The fresher the egg, the harder it is to peel after boiling.",
  "Sugar isn’t just for sweetness—it affects texture, moisture, and browning.",
  "A “pinch” is technically 1/16 of a teaspoon.",
  "Salt can suppress bitterness in foods like broccoli or coffee.",
  "The word “restaurant” comes from a French word meaning “to restore.”",
  "Curry is not a single dish—it refers to a variety of spiced dishes across South Asia.",
  "Sushi originally preserved fish by fermenting it in rice.",
  "The croissant was inspired by Austrian kipferl, not originally French.",
  "India has over 100 types of lentils used in regional cooking.",
  "Pasta is likely derived from ancient Asian noodles, not solely Italian.",
  "Kimchi can be aged for months or even years in underground cellars.",
  "Chocolate originated as a bitter ceremonial drink in Mesoamerica.",
  "Bread was used as a plate before modern dishes existed.",
  "Tomatoes were once considered poisonous in Europe.",
  "The hottest chili in the world is the Carolina Reaper (over 2 million Scoville units).",
  "Water doesn’t mix with oil because of molecular polarity.",
  "Cooking pasta without salt makes it bland—salt is essential in boiling water.",
  "Wooden spoons don’t conduct heat, making them great for stirring hot food.",
  "Microwave ovens were invented accidentally during radar research.",
  "You can make whipped cream with just cream and a mason jar (shake hard!).",
  "Overcooking garlic turns it bitter instead of sweet.",
  "Tasting raw flour or batter can lead to foodborne illness due to E. coli.",
];

const QuoteGenerator = () => {
  const randomIndex = Math.floor(Math.random() * quotes.length);
  const quote = quotes[randomIndex];

  return (
    <div className="quote-generator">
      <h2 className="quote-text">"{quote}"</h2>
    </div>
  );
};

export default QuoteGenerator;